services:
  dev-env:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - USER_ID=${DUID}
        - GROUP_ID=${DGID}
        - USER=${USER}

    user: "${DUID}:${DGID}"

    volumes:
      - ~/.gitconfig:/home/${USER}/.gitconfig
      - ~/.ssh:/home/${USER}/.ssh
      - .:/home/${USER}/app
      - .vscode-server:/home/${USER}/.vscode-server/

    restart: always

    links:
      - influx-db:influx-db

    ports:
      - 8080:8080
    tty: true

  influx-db:
    image: influxdb
    volumes:
      - .influx/data:/var/lib/influxdb2
      - .influx/config:/etc/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=dev
      - DOCKER_INFLUXDB_INIT_PASSWORD=dev-password
      - DOCKER_INFLUXDB_INIT_ORG=dev
      - DOCKER_INFLUXDB_INIT_BUCKET=dev
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=dev-token
    ports:
      - 8086:8086
